//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CategoryPJ.Models.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temp_User()
        {
            this.SendMails = new HashSet<SendMail>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int TempID { get; set; }
        public string Message { get; set; }
        public string Title { get; set; }
        public string photo { get; set; }
        public string music { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendMail> SendMails { get; set; }
        public virtual Template Template { get; set; }
        public virtual User User { get; set; }
    }
}
