//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baitap2
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emp()
        {
            this.emp1 = new HashSet<emp>();
        }
    
        public int empNo { get; set; }
        public string Ename { get; set; }
        public string job { get; set; }
        public Nullable<int> Mgr { get; set; }
        public Nullable<System.DateTime> hireDate { get; set; }
        public Nullable<decimal> sal { get; set; }
        public Nullable<decimal> comm { get; set; }
        public Nullable<int> DeptNo { get; set; }
    
        public virtual Dept Dept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp> emp1 { get; set; }
        public virtual emp emp2 { get; set; }
    }
}
