//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoProject1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dept()
        {
            this.emps = new HashSet<emp>();
        }

        public Dept(int deptNo, string dName, string loc, ICollection<emp> emps)
        {
            DeptNo = deptNo;
            DName = dName;
            this.loc = loc;
            this.emps = emps;
        }

        public int DeptNo { get; set; }
        public string DName { get; set; }
        public string loc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp> emps { get; set; }
    }
}
