//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoProject1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalGrade
    {
        public SalGrade(int grade, decimal? losal, decimal? hisal)
        {
            this.grade = grade;
            this.losal = losal;
            this.hisal = hisal;
        }

        public int grade { get; set; }
        public Nullable<decimal> losal { get; set; }
        public Nullable<decimal> hisal { get; set; }
    }
}
