//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CategoryPJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public int ID { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
