//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models.ModelsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int id { get; set; }
        public Nullable<int> idusr { get; set; }
        public Nullable<int> idfriend { get; set; }
        public string contentpath { get; set; }
        public Nullable<bool> unfriend { get; set; }
    
        public virtual UserChat UserChat { get; set; }
        public virtual UserChat UserChat1 { get; set; }
    }
}
