//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models.ModelsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupDetail
    {
        public int id { get; set; }
        public Nullable<int> IDG { get; set; }
        public Nullable<int> IDU { get; set; }
    
        public virtual GroupChat GroupChat { get; set; }
        public virtual UserChat UserChat { get; set; }
    }
}
