//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerSystem.Models.ModelsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportDetail
    {
        public int Id { get; set; }
        public int Account_Id { get; set; }
        public int Owner_Id { get; set; }
        public int Transport_Id { get; set; }
        public int TransType_Id { get; set; }
        public int Region_Id { get; set; }
        public string Color { get; set; }
        public string License_Plate { get; set; }
        public bool status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ownerDetail ownerDetail { get; set; }
        public virtual Regional Regional { get; set; }
        public virtual TransportType TransportType { get; set; }
        public virtual TransportPart TransportPart { get; set; }
    }
}
